# Generated by Django 4.2.7 on 2024-03-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_reg', '0002_phoneuser_rename_email_otpverifiaction_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-03-19', max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='date',
            field=models.CharField(default='2024-03-19', max_length=10),
        ),
    ]
