# Generated by Django 4.2.7 on 2023-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2332)),
                ("task", models.CharField(max_length=2332)),
                ("task_date", models.CharField(default="null", max_length=255)),
                ("report_of_work", models.CharField(max_length=2332)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("25%", "25%"),
                            ("50%", "50%"),
                            ("75%", "75%"),
                            ("100%", "100%"),
                        ],
                        default="25%",
                        max_length=128,
                    ),
                ),
                ("documnet", models.FileField(null=True, upload_to="")),
                ("comment", models.CharField(max_length=2332)),
                ("document_base64", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
