# Generated by Django 4.2.7 on 2023-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=2322)),
                ("password", models.CharField(max_length=2322)),
                ("name", models.CharField(max_length=2322, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssignTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tl_name", models.CharField(blank=True, max_length=255, null=True)),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                ("due_date", models.CharField(blank=True, max_length=255, null=True)),
                ("overdue_duedate", models.BooleanField(default=False)),
                ("task_done", models.BooleanField(default=False)),
                ("push_code", models.BooleanField(default=False)),
                ("dev_review", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(default="", max_length=2322)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeLogin2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("login_time", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude1", models.CharField(blank=True, max_length=255, null=True)),
                ("lattiude1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logout_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("longitude2", models.CharField(blank=True, max_length=255, null=True)),
                ("lattiude2", models.CharField(blank=True, max_length=255, null=True)),
                ("total_time", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_images/")),
                ("userid", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("image_base64", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
