# Generated by Django 4.2.7 on 2023-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_assigntask_add_photo_assigntask_deployment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigntask",
            name="addphoto_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
