# Generated by Django 4.2.7 on 2023-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_assigntask_addphoto_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeelogin",
            name="tl",
            field=models.BooleanField(default=False),
        ),
    ]
