# Generated by Django 4.2.7 on 2023-11-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_employeelogin_tl"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("confirm_password", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
