# Generated by Django 4.2.7 on 2023-11-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
