# Generated by Django 4.2.7 on 2023-12-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeJoining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeName", models.CharField(max_length=255)),
                ("employeeId", models.CharField(max_length=50)),
                ("totalwork", models.CharField(max_length=50)),
                ("leaves", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                ("dateOfJoining", models.CharField(max_length=20)),
                ("month", models.CharField(max_length=10)),
                ("year", models.CharField(max_length=4)),
                ("basicDA", models.CharField(max_length=50)),
                ("providentFund", models.CharField(max_length=50)),
                ("hra", models.CharField(max_length=50)),
                ("esi", models.CharField(max_length=50)),
                ("conveyance", models.CharField(max_length=50)),
                ("loan", models.CharField(max_length=50)),
                ("professionTax", models.CharField(max_length=50)),
                ("lop", models.CharField(max_length=50)),
                ("totalAddition", models.CharField(max_length=50)),
                ("totalDeduction", models.CharField(max_length=50)),
                ("netSalary", models.CharField(max_length=50)),
            ],
        ),
    ]
