# Generated by Django 4.2.7 on 2023-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_employeejoining"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeelogin",
            name="backend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeelogin",
            name="backend_tl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeelogin",
            name="testing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeelogin",
            name="testing_tl",
            field=models.BooleanField(default=False),
        ),
    ]
