# Generated by Django 4.2.7 on 2023-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_assigntask_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeejoining",
            name="acc_num",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="bank_name",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="branch_name",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="extrafil_1",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="extrafil_2",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="ifsc",
            field=models.CharField(default=False, max_length=255),
        ),
    ]
