# Generated by Django 4.2.7 on 2024-01-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_employeejoining_acc_num_employeejoining_bank_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(default="null", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("terms_and_conditions", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
