# Generated by Django 4.2.7 on 2024-02-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminauth",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assigntask",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeedetails",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeelogin",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeelogin2",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="organization",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
