# Generated by Django 4.2.7 on 2024-02-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_adminauth_organization_assigntask_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("", "Select..."),
                            ("Tl", "Tl"),
                            ("Testing", "Testing"),
                            ("Testing_tl", "Testing tl"),
                            ("Backend", "Backend"),
                            ("Backend_tl", "Backend tl"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
