# Generated by Django 4.2.7 on 2024-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_adduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adduser",
            name="role",
        ),
        migrations.AddField(
            model_name="adduser",
            name="backend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adduser",
            name="backend_tl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adduser",
            name="testing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adduser",
            name="testing_tl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adduser",
            name="tl",
            field=models.BooleanField(default=False),
        ),
    ]
