# Generated by Django 4.2.7 on 2024-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_remove_adduser_role_adduser_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigntask",
            name="dummyone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assigntask",
            name="postdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assigntask",
            name="tester",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
