# Generated by Django 4.2.7 on 2024-02-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_assigntask_postdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginprofile",
            name="casual_leave",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="earned_leave",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="facebook_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="insta_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="linkedin_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="marital_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="rating",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="reporting_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="sick_leave",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="twitter_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginprofile",
            name="working_since",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
