# Generated by Django 4.2.7 on 2024-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0018_loginprofile_casual_leave_loginprofile_earned_leave_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("tlname", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=255)),
                ("leave_type", models.CharField(max_length=50)),
                ("posted_date", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="leave_images/"),
                ),
                ("from_date", models.CharField(max_length=100)),
                ("to_date", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("admin_approve", models.BooleanField(default=False)),
                ("admin_cancel", models.BooleanField(default=False)),
                ("tl_approve", models.BooleanField(default=False)),
                ("tl_cancel", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("department", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=255)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="media_images/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="media_images/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="media_images/"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="media_videos/"),
                ),
                ("checkbox", models.BooleanField(default=False)),
            ],
        ),
    ]
