# Generated by Django 4.2.7 on 2024-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_applyleaves_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="loginprofile",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
