# Generated by Django 4.2.7 on 2024-02-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_applyleaves_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyleaves",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick_leave", "Sick Leave"),
                    ("casual_leave", "Casual Leave"),
                ],
                max_length=50,
            ),
        ),
    ]
