# Generated by Django 4.2.7 on 2024-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_applyleaves_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeelogin2",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeelogin2",
            name="lunch_break_checkin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeelogin2",
            name="lunch_break_checkout",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeelogin2",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
