# Generated by Django 4.2.7 on 2024-02-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_employeelogin2_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WantedApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="api_images/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
