# Generated by Django 4.2.7 on 2024-02-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_wantedapi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="api_images/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="wantedapi",
            name="images",
        ),
        migrations.AddField(
            model_name="wantedapi",
            name="images",
            field=models.ManyToManyField(blank=True, to="account.image"),
        ),
    ]
