# Generated by Django 4.2.7 on 2024-02-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_image_remove_wantedapi_images_wantedapi_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wantedapi",
            name="description",
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="wantedapi",
            name="title",
            field=models.CharField(blank=True, default=False, max_length=255),
        ),
    ]
