# Generated by Django 4.2.7 on 2024-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_alter_wantedapi_description_alter_wantedapi_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="feed_images/")),
                ("date", models.CharField(max_length=100)),
                ("desc", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="wantedapi",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="wantedapi",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="wantedapi",
            name="images",
            field=models.ManyToManyField(to="account.image"),
        ),
        migrations.AlterField(
            model_name="wantedapi",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
