# Generated by Django 4.2.7 on 2024-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_feed_alter_image_image_alter_wantedapi_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="WantedApi2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="media_videos/"),
                ),
                ("description", models.TextField()),
                ("organization", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=100)),
                ("images", models.ManyToManyField(to="account.image")),
            ],
        ),
    ]
