# Generated by Django 4.2.7 on 2024-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0030_image3_alter_wantedapi2_images_adminapi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminapi",
            old_name="upload_images",
            new_name="images",
        ),
    ]
