# Generated by Django 4.2.7 on 2024-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0031_rename_upload_images_adminapi_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
