# Generated by Django 4.2.7 on 2024-02-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0035_alter_adminapi_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminapi",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="adminapi",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="adminapi",
            name="organization",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
