# Generated by Django 4.2.7 on 2024-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_adminapi_email_alter_adminapi_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntask',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
    ]
