# Generated by Django 4.2.7 on 2024-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_assigntask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleaves',
            name='leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
