# Generated by Django 4.2.7 on 2024-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_applyleaves_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('websiteurl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loginprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wantedapi',
            name='event_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
