# Generated by Django 4.2.7 on 2024-03-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_trustedcompany_loginprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed_images/'),
        ),
    ]
