# Generated by Django 4.2.7 on 2024-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_employeeapprovdetails_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
