# Generated by Django 4.2.7 on 2024-03-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
