# Generated by Django 4.2.7 on 2024-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_remove_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
