# Generated by Django 4.2.7 on 2024-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapi',
            name='password2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
