# Generated by Django 4.2.7 on 2024-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_alter_wantedapi_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(default='null', max_length=255, primary_key=True, serialize=False),
        ),
    ]
